--- #YAML:1.0
name:               SVN-Access
version:            0.08
abstract:           Perl extension to manipulate SVN Access files
author:
    - Michael Gregorowicz <mike@mg2.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Tie::IxHash:  1.21
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
