--- #YAML:1.0
name:                SVN-Access
version:             0.06
abstract:            Perl extension to manipulate SVN Access files
license:             ~
author:              
    - Michael Gregorowicz <mike@mg2.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Tie::IxHash:                   1.21
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
