---
abstract: 'Perl extension to manipulate SVN Access files'
author:
  - 'Michael Gregorowicz <mike@mg2.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SVN-Access
no_index:
  directory:
    - t
    - inc
requires:
  Tie::IxHash: 1.21
version: 0.09
